local E, L, V, P, G = unpack(ElvUI)
local NUI = E:GetModule("NotUI")

function NUI:LoadWarpDepleteProfile()

WarpDepleteDB = {
	["char"] = {
	},
	["global"] = {
		["mdtAlertShown"] = true,
	},
	["profileKeys"] = {
	},
	["profiles"] = {
		["Main"] = {
			["customForcesFormat"] = ":percent: |||| :count:/:totalcount:",
			["bar3TextureColor"] = "fff26420",
			["bar2Font"] = "NotUI Font light",
			["objectivesFont"] = "NotUI Font light",
			["timerSuccessColor"] = "ff40ff00",
			["bar2Texture"] = "Melli",
			["keyDetailsFont"] = "NotUI Font light",
			["bar1TextureColor"] = "fff26420",
			["forcesTexture"] = "Melli",
			["forcesColor"] = "ffffffff",
			["forcesFont"] = "NotUI Font light",
			["timerExpiredColor"] = "ffc50a00",
			["showTooltipCount"] = false,
			["barWidth"] = 370,
			["forcesFormat"] = ":custom:",
			["forcesOverlayTexture"] = "Melli",
			["forcesGlowLineCount"] = 10,
			["frameY"] = 102.4340057373047,
			["deathsFont"] = "NotUI Font light",
			["barHeight"] = 8,
			["verticalOffset"] = 0,
			["keyDetailsColor"] = "ff00aaff",
			["customCurrentPullFormat"] = "(+:percent:) ||||",
			["bar3Font"] = "NotUI Font light",
			["forcesGlowColor"] = "fffff500",
			["bar3Texture"] = "Melli",
			["completedObjectivesColor"] = "ff40ff00",
			["bar1Font"] = "NotUI Font light",
			["bar2TextureColor"] = "fff26420",
			["forcesGlowFrequency"] = 0.2,
			["timerFont"] = "NotUI Font Heavy",
			["forcesOverlayTextureColor"] = "ffffffff",
			["completedForcesColor"] = "ff40ff00",
			["forcesTextureColor"] = "ff00aaff",
			["keyColor"] = "ffa5a6ac",
			["forcesGlowLength"] = 2,
			["currentPullFormat"] = ":custom:",
			["forcesFontSize"] = 14,
			["objectivesOffset"] = 1.38,
			["bar1Texture"] = "Melli",
			["frameX"] = -24.23313331604004,
			["forcesGlowThickness"] = 1.4,
			["demoForcesGlow"] = true,
			["showPrideGlow"] = false,
			["keyFont"] = "NotUI Font light",
		},
		["Default"] = {
			["customForcesFormat"] = ":percent: |||| :count:/:totalcount:",
			["barHeight"] = 8,
			["timerSuccessColor"] = "ff40ff00",
			["forcesFont"] = "NotUI Font light",
			["showTooltipCount"] = false,
			["forcesFormat"] = ":custom:",
			["verticalOffset"] = 0,
			["frameX"] = -24.23313331604004,
			["completedObjectivesColor"] = "ff40ff00",
			["currentPullFormat"] = ":custom:",
			["timerFont"] = "NotUI Font Heavy",
			["bar3Font"] = "NotUI Font light",
			["keyDetailsColor"] = "ff00aaff",
			["forcesGlowThickness"] = 1.4,
			["showPrideGlow"] = false,
			["bar3TextureColor"] = "fff26420",
			["objectivesFont"] = "NotUI Font light",
			["keyColor"] = "ffa5a6ac",
			["forcesGlowColor"] = "fffff500",
			["bar2Texture"] = "Melli",
			["keyDetailsFont"] = "NotUI Font light",
			["forcesGlowFrequency"] = 0.2,
			["deathsFont"] = "NotUI Font light",
			["timerExpiredColor"] = "ffc50a00",
			["forcesOverlayTexture"] = "Melli",
			["forcesGlowLength"] = 2,
			["bar2Font"] = "NotUI Font light",
			["demoForcesGlow"] = true,
			["bar3Texture"] = "Melli",
			["completedForcesColor"] = "ff40ff00",
			["bar1TextureColor"] = "fff26420",
			["bar1Font"] = "NotUI Font light",
			["forcesOverlayTextureColor"] = "ffffffff",
			["forcesTexture"] = "Melli",
			["objectivesOffset"] = 1.38,
			["frameY"] = 102.4340057373047,
			["forcesTextureColor"] = "ff00aaff",
			["forcesGlowLineCount"] = 10,
			["barWidth"] = 370,
			["forcesFontSize"] = 14,
			["customCurrentPullFormat"] = "(+:percent:) ||||",
			["bar1Texture"] = "Melli",
			["forcesColor"] = "ffffffff",
			["bar2TextureColor"] = "fff26420",
			["keyFont"] = "NotUI Font light",
		},
		["Nöthing - Burning Legion"] = {
		},
	},
}

end