local E, L, V, P, G = unpack(ElvUI)
local NUI = E:GetModule("NotUI")


function NUI:DPSActionBars()
	--setup action bars visibility
	E.db["actionbar"]["bar1"]["enabled"] = true
	E.db["actionbar"]["bar2"]["enabled"] = true
	E.db["actionbar"]["bar3"]["enabled"] = true
	E.db["actionbar"]["bar4"]["enabled"] = true
	E.db["actionbar"]["bar5"]["enabled"] = true
	E.db["actionbar"]["bar6"]["enabled"] = false
	E.db["actionbar"]["bar7"]["enabled"] = false
	E.db["actionbar"]["bar8"]["enabled"] = false
	E.db["actionbar"]["bar9"]["enabled"] = false
	
	--setup button amount for active bars
	E.db["actionbar"]["bar1"]["buttons"] = 12
	E.db["actionbar"]["bar2"]["buttons"] = 12
	E.db["actionbar"]["bar3"]["buttons"] = 12
	E.db["actionbar"]["bar4"]["buttons"] = 12
	E.db["actionbar"]["bar5"]["buttons"] = 12
	
	--settings for all action bars
	E.db["actionbar"]["bar1"]["backdrop"] = true
	E.db["actionbar"]["bar1"]["mouseover"] = true
	E.db["actionbar"]["bar1"]["buttonSize"] = 30
	E.db["actionbar"]["bar1"]["countFont"] = "NotUI Font light"
	E.db["actionbar"]["bar1"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar1"]["countFontSize"] = 13
	E.db["actionbar"]["bar1"]["flyoutDirection"] = "UP"
	E.db["actionbar"]["bar1"]["hotkeyFont"] = "NotUI Font light"
	E.db["actionbar"]["bar1"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar1"]["hotkeyFontSize"] = 13
	E.db["actionbar"]["bar1"]["macroFont"] = "NotUI Font light"
	E.db["actionbar"]["bar1"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar1"]["macroFontSize"] = 13
	E.db["actionbar"]["bar10"]["countFont"] = "NotUI Font light"
	E.db["actionbar"]["bar10"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar10"]["countFontSize"] = 13
	E.db["actionbar"]["bar10"]["hotkeyFont"] = "NotUI Font light"
	E.db["actionbar"]["bar10"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar10"]["hotkeyFontSize"] = 13
	E.db["actionbar"]["bar10"]["macroFont"] = "NotUI Font light"
	E.db["actionbar"]["bar10"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar10"]["macroFontSize"] = 13
	E.db["actionbar"]["bar13"]["countFont"] = "NotUI Font light"
	E.db["actionbar"]["bar13"]["hotkeyFont"] = "NotUI Font light"
	E.db["actionbar"]["bar14"]["countFont"] = "NotUI Font light"
	E.db["actionbar"]["bar14"]["hotkeyFont"] = "NotUI Font light"
	E.db["actionbar"]["bar15"]["countFont"] = "NotUI Font light"
	E.db["actionbar"]["bar15"]["hotkeyFont"] = "NotUI Font light"
	E.db["actionbar"]["bar2"]["backdrop"] = true
	E.db["actionbar"]["bar2"]["mouseover"] = true
	E.db["actionbar"]["bar2"]["buttonSize"] = 30
	E.db["actionbar"]["bar2"]["countFont"] = "NotUI Font light"
	E.db["actionbar"]["bar2"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar2"]["countFontSize"] = 13
	E.db["actionbar"]["bar2"]["flyoutDirection"] = "UP"
	E.db["actionbar"]["bar2"]["hotkeyFont"] = "NotUI Font light"
	E.db["actionbar"]["bar2"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar2"]["hotkeyFontSize"] = 13
	E.db["actionbar"]["bar2"]["macroFont"] = "NotUI Font light"
	E.db["actionbar"]["bar2"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar2"]["macroFontSize"] = 13
	E.db["actionbar"]["bar3"]["backdrop"] = true
	E.db["actionbar"]["bar3"]["mouseover"] = true
	E.db["actionbar"]["bar3"]["buttonSize"] = 30
	E.db["actionbar"]["bar3"]["buttons"] = 12
	E.db["actionbar"]["bar3"]["buttonsPerRow"] = 12
	E.db["actionbar"]["bar3"]["countFont"] = "NotUI Font light"
	E.db["actionbar"]["bar3"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar3"]["countFontSize"] = 13
	E.db["actionbar"]["bar3"]["flyoutDirection"] = "LEFT"
	E.db["actionbar"]["bar3"]["hotkeyFont"] = "NotUI Font light"
	E.db["actionbar"]["bar3"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar3"]["hotkeyFontSize"] = 13
	E.db["actionbar"]["bar3"]["macroFont"] = "NotUI Font light"
	E.db["actionbar"]["bar3"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar3"]["macroFontSize"] = 13
	E.db["actionbar"]["bar4"]["buttonSize"] = 30
	E.db["actionbar"]["bar4"]["backdrop"] = true
	E.db["actionbar"]["bar4"]["mouseover"] = true
	E.db["actionbar"]["bar4"]["buttonsPerRow"] = 12
	E.db["actionbar"]["bar4"]["countFont"] = "NotUI Font light"
	E.db["actionbar"]["bar4"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar4"]["countFontSize"] = 13
	E.db["actionbar"]["bar4"]["flyoutDirection"] = "UP"
	E.db["actionbar"]["bar4"]["hotkeyFont"] = "NotUI Font light"
	E.db["actionbar"]["bar4"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar4"]["hotkeyFontSize"] = 13
	E.db["actionbar"]["bar4"]["macroFont"] = "NotUI Font light"
	E.db["actionbar"]["bar4"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar4"]["macroFontSize"] = 13
	E.db["actionbar"]["bar4"]["point"] = "BOTTOMLEFT"
	E.db["actionbar"]["bar5"]["backdrop"] = true
	E.db["actionbar"]["bar5"]["mouseover"] = true
	E.db["actionbar"]["bar5"]["buttonSize"] = 30
	E.db["actionbar"]["bar5"]["buttons"] = 12
	E.db["actionbar"]["bar5"]["buttonsPerRow"] = 12
	E.db["actionbar"]["bar5"]["countFont"] = "NotUI Font light"
	E.db["actionbar"]["bar5"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar5"]["countFontSize"] = 13
	E.db["actionbar"]["bar5"]["flyoutDirection"] = "UP"
	E.db["actionbar"]["bar5"]["hotkeyFont"] = "NotUI Font light"
	E.db["actionbar"]["bar5"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar5"]["hotkeyFontSize"] = 13
	E.db["actionbar"]["bar5"]["macroFont"] = "NotUI Font light"
	E.db["actionbar"]["bar5"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar5"]["macroFontSize"] = 13
	E.db["actionbar"]["barPet"]["buttonSize"] = 27
	E.db["actionbar"]["barPet"]["buttonsPerRow"] = 10
	E.db["actionbar"]["barPet"]["countFont"] = "NotUI Font light"
	E.db["actionbar"]["barPet"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["barPet"]["countFontSize"] = 13
	E.db["actionbar"]["barPet"]["hotkeyFont"] = "NotUI Font light"
	E.db["actionbar"]["barPet"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["barPet"]["hotkeyFontSize"] = 13
	E.db["actionbar"]["extraActionButton"]["hotkeyFont"] = "NotUI Font light"
	E.db["actionbar"]["extraActionButton"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["extraActionButton"]["hotkeyFontSize"] = 13
	E.db["actionbar"]["font"] = "NotUI Font light"
	E.db["actionbar"]["fontOutline"] = "OUTLINE"
	E.db["actionbar"]["fontSize"] = 13
	E.db["actionbar"]["microbar"]["backdrop"] = true
	E.db["actionbar"]["microbar"]["buttonHeight"] = 24
	E.db["actionbar"]["microbar"]["buttonSize"] = 24
	E.db["actionbar"]["microbar"]["buttonSpacing"] = 1
	E.db["actionbar"]["microbar"]["mouseover"] = true
	E.db["actionbar"]["stanceBar"]["backdrop"] = true
	E.db["actionbar"]["stanceBar"]["backdropSpacing"] = 1
	E.db["actionbar"]["stanceBar"]["buttonSize"] = 30
	E.db["actionbar"]["stanceBar"]["buttonSpacing"] = 3
	E.db["actionbar"]["stanceBar"]["buttons"] = 5
	E.db["actionbar"]["stanceBar"]["buttonsPerRow"] = 1
	E.db["actionbar"]["stanceBar"]["hotkeyFont"] = "NotUI Font light"
	E.db["actionbar"]["stanceBar"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["stanceBar"]["point"] = "TOPRIGHT"
	E.db["actionbar"]["vehicleExitButton"]["hotkeyFont"] = "NotUI Font light"
	E.db["actionbar"]["vehicleExitButton"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["vehicleExitButton"]["hotkeyFontSize"] = 13
	E.db["actionbar"]["microbar"]["backdrop"] = true
	E.db["actionbar"]["microbar"]["buttonHeight"] = 24
	E.db["actionbar"]["microbar"]["buttonSize"] = 24
	E.db["actionbar"]["microbar"]["buttonSpacing"] = 1
	E.db["actionbar"]["microbar"]["mouseover"] = true
	E.db["actionbar"]["stanceBar"]["backdrop"] = true
	E.db["actionbar"]["stanceBar"]["buttonsPerRow"] = 1
	E.db["actionbar"]["stanceBar"]["hotkeyFont"] = "NotUI Font light"
	E.db["actionbar"]["stanceBar"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["stanceBar"]["point"] = "TOPRIGHT"
	E.db["actionbar"]["vehicleExitButton"]["hotkeyFont"] = "NotUI Font light"
	E.db["actionbar"]["vehicleExitButton"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["vehicleExitButton"]["hotkeyFontSize"] = 13
	E.db["actionbar"]["microbar"]["backdrop"] = true
	E.db["actionbar"]["microbar"]["buttonHeight"] = 24
	E.db["actionbar"]["microbar"]["buttonSize"] = 24
	E.db["actionbar"]["microbar"]["buttonSpacing"] = 1
	E.db["actionbar"]["microbar"]["mouseover"] = true
	E.db["actionbar"]["stanceBar"]["backdrop"] = true
	E.db["actionbar"]["stanceBar"]["buttonsPerRow"] = 1
	E.db["actionbar"]["stanceBar"]["hotkeyFont"] = "NotUI Font light"
	E.db["actionbar"]["stanceBar"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["stanceBar"]["point"] = "TOPRIGHT"
	E.db["actionbar"]["vehicleExitButton"]["hotkeyFont"] = "NotUI Font light"
	E.db["actionbar"]["vehicleExitButton"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["vehicleExitButton"]["hotkeyFontSize"] = 13
end